function [sd_num,sd_name,sd_G1,sd_Gz,sd_xa0,sd_xaz,sd_dhn,sd_e,sd_n,sd_ln,sd_minn,sd_omiga,sd_alpha1,sd_p0,sd_h0,sd_hz,sd_pz,sd_thetz,sd_alphaz2,sd_hcz2,sd_dline,sd_xaline,sd_divide,sd_a,sd_Ka]=Known_stagedistribute_parameters
%******************************************************
%分级计算所需参数(50MW)
%sd_num汽缸数,sd_name缸名称,sd_G1第一级流量(kg/s),sd_Gz末级流量(kg/s),sd_xa0第一级速比（估计）,sd_xaz末级速比
%sd_dhn第一级喷嘴比焓降（估计）(kJ/kg),sd_e第一级部分进汽度,sd_n转速,sd_ln第一级喷最高度（mm）
%sd_minn第一级流量系数,sd_omiga第一级反动度，sd_alpha1第一级进汽角,sd_p0第一级级前压力(MPa),
%sd_h0第一级级前比焓值(kJ/kg),sd_hz末级级后焓值(m^3/kg),sd_pz末级级后压力(MPa),sd_thetz末级径高比
%sd_alphaz2末级出汽角,sd_hcz2末级损失(kJ/kg),sd_line汽缸直径变化趋势线,sd_xaline速比变化趋势线,
%sd_divide初分级数,,sd_a,sd_Ka系数
% ****作者：王雷 zrqwl2003@126.com***
%******************************************************
%需要自行修改和输入
sd_num=1;
%对于多缸情况，以下参数均采用数组的形式
sd_name={'单缸'};
%第一级流量
sd_G1=100;
%末级流量
sd_Gz=20;
%第一级速度比
sd_xa0=0.588;
%末级速度比
sd_xaz=0.6252;
%第一级喷嘴比焓降
sd_dhn=130;
%第一级部分进气度
sd_e=1;
%第一级转速
sd_n=3000;
%第一级喷嘴高度
sd_ln=20;
%第一级喷嘴流量系数
sd_minn=0.97;
%第一级反动度
sd_omiga=0.05;
%第一级进气角
sd_alpha1=14.78;
%第一级级前压力
sd_p0=12.1674;
%第一级级前比焓值
sd_h0=3331.32;
%末级级后比焓值
sd_hz=3019.95;
%末级级后压力
sd_pz=3.622;
%末级径高比
sd_thetz=10.52;
%末级出气角
sd_alphaz2=90;
%末级损失
sd_hcz2=1.25;
%汽缸直径变化趋势线
sd_dline=[0,0,0,0,41,739;];
%速比变化趋势线
sd_xaline=[0,0,0,0,0.0062,0.5818;];
%初分级数
sd_divide=7;
%系数
sd_a=0.04;
sd_Ka=4.8e-4;